#!/bin/bash

# XDG paths
export XDG_DESKTOP_DIR="$HOME/"
export XDG_DOCUMENTS_DIR="$HOME/Documents/"
export XDG_DOWNLOAD_DIR="$HOME/Downloads/"
export XDG_MUSIC_DIR="$HOME/Music/"
export XDG_PICTURES_DIR="$HOME/Pictures/"
export XDG_VIDEOS_DIR="$HOME/Music/"
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$XDG_CONFIG_HOME/cache
export XDG_DATA_HOME=$HOME/.local/share

# PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.local/lib:$PATH
export PATH=$HOME/.local/share/cargo/bin:$PATH

# HISTORY
export HISTSIZE=2000
export HISTFILESIZE=2000
export HISTCONTROL=ignoredups

# Python
export PYTHONHISTFILE=/dev/null

# Rust
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CARGO_HOME="$XDG_DATA_HOME/cargo"

# Go
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"

# General exports
export LESSHISTFILE=-
export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="foot"

# Extras
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_pro_icd64.json
export ANSIBLE_CONFIG=$XDG_CONFIG_HOME/ansible/ansible.cfg
export KUBECONFIG="$XDG_CONFIG_HOME/kube"
